### ISSUE TITLE
don't work

### ISSUE THREAD

**Issue by Lage4kaa** [thinkdev1/jss-brawl-33#1]
don't work lol

**Comment by thinkdev1** [comment]
xd. what not work?

**Comment by thinkdev1** [comment]
if error 'module not found' you    dudnik

**Comment by Lage4kaa** [comment]
> if error 'module not found' you dudnik

there is always training🫨

**Comment by thinkdev1** [comment]
please send error

**Comment by thinkdev1** [comment]
ohd is working, check client
